// <auto-generated />
using System;
using Edzoterem.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Edzoterem.Infrastructure.Migrations
{
    [DbContext(typeof(EdzoteremDbContext))]
    partial class EdzoteremDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Edzoterem.Domain.Entities.Berlet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ArFizetve")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("BerletTipusId")
                        .HasColumnType("int");

                    b.Property<int?>("HatralevoAlkalmak")
                        .HasColumnType("int");

                    b.Property<DateOnly>("KezdoDatum")
                        .HasColumnType("date");

                    b.Property<DateOnly>("LejaratiDatum")
                        .HasColumnType("date");

                    b.Property<int>("LetrehozvaAltalId")
                        .HasColumnType("int");

                    b.Property<int>("Statusz")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BerletTipusId");

                    b.HasIndex("LetrehozvaAltalId");

                    b.HasIndex("TagId");

                    b.ToTable("Berletek");
                });

            modelBuilder.Entity("Edzoterem.Domain.Entities.BerletTipus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktiv")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("AlapertelmezettAlkalmak")
                        .HasColumnType("int");

                    b.Property<decimal>("Ar")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Kategoria")
                        .HasColumnType("int");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("BerletTipusok");
                });

            modelBuilder.Entity("Edzoterem.Domain.Entities.CsoportosFoglalkozas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EdzoId")
                        .HasColumnType("int");

                    b.Property<string>("ElutasitasIndoka")
                        .HasColumnType("longtext");

                    b.Property<string>("Helyszin")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Idopont")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("JovahagyasDatuma")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("JovahagytaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LezarasDatuma")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MaxLetszam")
                        .HasColumnType("int");

                    b.Property<int>("MeghirdetteId")
                        .HasColumnType("int");

                    b.Property<string>("Megnevezes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Statusz")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EdzoId");

                    b.HasIndex("JovahagytaId");

                    b.HasIndex("MeghirdetteId");

                    b.ToTable("CsoportosFoglalkozasok");
                });

            modelBuilder.Entity("Edzoterem.Domain.Entities.CsoportosJelentkezes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CsoportosFoglalkozasId")
                        .HasColumnType("int");

                    b.Property<bool?>("JelenVolt")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("JelentkezesDatuma")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RogzitveAltalId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RogzitveAltalId");

                    b.HasIndex("TagId");

                    b.HasIndex("CsoportosFoglalkozasId", "TagId")
                        .IsUnique();

                    b.ToTable("CsoportosJelentkezesek");
                });

            modelBuilder.Entity("Edzoterem.Domain.Entities.Dolgozo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adoszam")
                        .HasColumnType("longtext");

                    b.Property<bool>("Aktiv")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Becenev")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("FenykepUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Keresztnev")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Letrehozva")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Megjegyzes")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Modositva")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MunkakorId")
                        .HasColumnType("int");

                    b.Property<int>("Nem")
                        .HasColumnType("int");

                    b.Property<decimal?>("Oradij")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("PortfolioUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("SzemelyiSzam")
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("SzuletesiDatum")
                        .HasColumnType("date");

                    b.Property<string>("TajSzam")
                        .HasColumnType("longtext");

                    b.Property<string>("Telefon")
                        .HasColumnType("longtext");

                    b.Property<string>("Vezeteknev")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("MunkakorId");

                    b.ToTable("Dolgozok");
                });

            modelBuilder.Entity("Edzoterem.Domain.Entities.Edzo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DolgozoId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Oradij")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Szakterulet")
                        .HasColumnType("longtext");

                    b.Property<string>("Vegzettseg")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DolgozoId")
                        .IsUnique();

                    b.ToTable("Edzok");
                });

            modelBuilder.Entity("Edzoterem.Domain.Entities.EdzoElerhetoseg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EdzoId")
                        .HasColumnType("int");

                    b.Property<int>("HetNapja")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("IgIdo")
                        .HasColumnType("time(6)");

                    b.Property<TimeOnly>("TolIdo")
                        .HasColumnType("time(6)");

                    b.HasKey("Id");

                    b.HasIndex("EdzoId");

                    b.ToTable("EdzoElerhetosegek");
                });

            modelBuilder.Entity("Edzoterem.Domain.Entities.EgyeniFoglalkozas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Allapot")
                        .HasColumnType("int");

                    b.Property<decimal>("Ar")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("DolgozoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Idopont")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Megjegyzes")
                        .HasColumnType("longtext");

                    b.Property<int>("RogzitveAltalId")
                        .HasColumnType("int");

                    b.Property<int>("SzolgaltatasTipusId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DolgozoId");

                    b.HasIndex("RogzitveAltalId");

                    b.HasIndex("SzolgaltatasTipusId");

                    b.HasIndex("TagId");

                    b.ToTable("EgyeniFoglalkozasok");
                });

            modelBuilder.Entity("Edzoterem.Domain.Entities.Felhasznalo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktiv")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("DolgozoId")
                        .HasColumnType("int");

                    b.Property<string>("Felhasznalonev")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("JelszoHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("JelszoIdeiglenes")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Szerepkor")
                        .HasColumnType("int");

                    b.Property<int?>("TagId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UtolsoBejelentkezes")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("DolgozoId")
                        .IsUnique();

                    b.HasIndex("Felhasznalonev")
                        .IsUnique();

                    b.HasIndex("TagId")
                        .IsUnique();

                    b.ToTable("Felhasznalok");
                });

            modelBuilder.Entity("Edzoterem.Domain.Entities.Munkakor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Munkakorok");
                });

            modelBuilder.Entity("Edzoterem.Domain.Entities.Munkarend", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Datum")
                        .HasColumnType("date");

                    b.Property<int>("DolgozoId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("IgIdo")
                        .HasColumnType("time(6)");

                    b.Property<string>("Megjegyzes")
                        .HasColumnType("longtext");

                    b.Property<TimeOnly>("TolIdo")
                        .HasColumnType("time(6)");

                    b.HasKey("Id");

                    b.HasIndex("DolgozoId");

                    b.ToTable("Munkarendek");
                });

            modelBuilder.Entity("Edzoterem.Domain.Entities.SzolgaltatasTipus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktiv")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("AlapertelmezettAr")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("SzolgaltatasTipusok");
                });

            modelBuilder.Entity("Edzoterem.Domain.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktiv")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Cim")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Keresztnev")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Megjegyzes")
                        .HasColumnType("longtext");

                    b.Property<int>("Nem")
                        .HasColumnType("int");

                    b.Property<DateOnly>("RegisztracioDatuma")
                        .HasColumnType("date");

                    b.Property<DateOnly>("SzuletesiDatum")
                        .HasColumnType("date");

                    b.Property<string>("Telefon")
                        .HasColumnType("longtext");

                    b.Property<string>("Vezeteknev")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("VhKapcsolattartoNev")
                        .HasColumnType("longtext");

                    b.Property<string>("VhKapcsolattartoTelefon")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Tagok");
                });

            modelBuilder.Entity("Edzoterem.Domain.Entities.Berlet", b =>
                {
                    b.HasOne("Edzoterem.Domain.Entities.BerletTipus", "BerletTipus")
                        .WithMany("Berletek")
                        .HasForeignKey("BerletTipusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Edzoterem.Domain.Entities.Felhasznalo", "LetrehozvaAltal")
                        .WithMany()
                        .HasForeignKey("LetrehozvaAltalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Edzoterem.Domain.Entities.Tag", "Tag")
                        .WithMany("Berletek")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BerletTipus");

                    b.Navigation("LetrehozvaAltal");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Edzoterem.Domain.Entities.CsoportosFoglalkozas", b =>
                {
                    b.HasOne("Edzoterem.Domain.Entities.Edzo", "Edzo")
                        .WithMany("CsoportosFoglalkozasok")
                        .HasForeignKey("EdzoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Edzoterem.Domain.Entities.Felhasznalo", "Jovahagyta")
                        .WithMany()
                        .HasForeignKey("JovahagytaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Edzoterem.Domain.Entities.Felhasznalo", "Meghirdette")
                        .WithMany()
                        .HasForeignKey("MeghirdetteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Edzo");

                    b.Navigation("Jovahagyta");

                    b.Navigation("Meghirdette");
                });

            modelBuilder.Entity("Edzoterem.Domain.Entities.CsoportosJelentkezes", b =>
                {
                    b.HasOne("Edzoterem.Domain.Entities.CsoportosFoglalkozas", "CsoportosFoglalkozas")
                        .WithMany("Jelentkezesek")
                        .HasForeignKey("CsoportosFoglalkozasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Edzoterem.Domain.Entities.Felhasznalo", "RogzitveAltal")
                        .WithMany()
                        .HasForeignKey("RogzitveAltalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Edzoterem.Domain.Entities.Tag", "Tag")
                        .WithMany("CsoportosJelentkezesek")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CsoportosFoglalkozas");

                    b.Navigation("RogzitveAltal");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Edzoterem.Domain.Entities.Dolgozo", b =>
                {
                    b.HasOne("Edzoterem.Domain.Entities.Munkakor", "Munkakor")
                        .WithMany("Dolgozok")
                        .HasForeignKey("MunkakorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Munkakor");
                });

            modelBuilder.Entity("Edzoterem.Domain.Entities.Edzo", b =>
                {
                    b.HasOne("Edzoterem.Domain.Entities.Dolgozo", "Dolgozo")
                        .WithOne("Edzo")
                        .HasForeignKey("Edzoterem.Domain.Entities.Edzo", "DolgozoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dolgozo");
                });

            modelBuilder.Entity("Edzoterem.Domain.Entities.EdzoElerhetoseg", b =>
                {
                    b.HasOne("Edzoterem.Domain.Entities.Edzo", "Edzo")
                        .WithMany("Elerhetosegek")
                        .HasForeignKey("EdzoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Edzo");
                });

            modelBuilder.Entity("Edzoterem.Domain.Entities.EgyeniFoglalkozas", b =>
                {
                    b.HasOne("Edzoterem.Domain.Entities.Dolgozo", "Dolgozo")
                        .WithMany()
                        .HasForeignKey("DolgozoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Edzoterem.Domain.Entities.Felhasznalo", "RogzitveAltal")
                        .WithMany()
                        .HasForeignKey("RogzitveAltalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Edzoterem.Domain.Entities.SzolgaltatasTipus", "SzolgaltatasTipus")
                        .WithMany("EgyeniFoglalkozasok")
                        .HasForeignKey("SzolgaltatasTipusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Edzoterem.Domain.Entities.Tag", "Tag")
                        .WithMany("EgyeniFoglalkozasok")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dolgozo");

                    b.Navigation("RogzitveAltal");

                    b.Navigation("SzolgaltatasTipus");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Edzoterem.Domain.Entities.Felhasznalo", b =>
                {
                    b.HasOne("Edzoterem.Domain.Entities.Dolgozo", "Dolgozo")
                        .WithOne("Felhasznalo")
                        .HasForeignKey("Edzoterem.Domain.Entities.Felhasznalo", "DolgozoId");

                    b.HasOne("Edzoterem.Domain.Entities.Tag", "Tag")
                        .WithOne("Felhasznalo")
                        .HasForeignKey("Edzoterem.Domain.Entities.Felhasznalo", "TagId");

                    b.Navigation("Dolgozo");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Edzoterem.Domain.Entities.Munkarend", b =>
                {
                    b.HasOne("Edzoterem.Domain.Entities.Dolgozo", "Dolgozo")
                        .WithMany("Munkarendek")
                        .HasForeignKey("DolgozoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dolgozo");
                });

            modelBuilder.Entity("Edzoterem.Domain.Entities.BerletTipus", b =>
                {
                    b.Navigation("Berletek");
                });

            modelBuilder.Entity("Edzoterem.Domain.Entities.CsoportosFoglalkozas", b =>
                {
                    b.Navigation("Jelentkezesek");
                });

            modelBuilder.Entity("Edzoterem.Domain.Entities.Dolgozo", b =>
                {
                    b.Navigation("Edzo");

                    b.Navigation("Felhasznalo");

                    b.Navigation("Munkarendek");
                });

            modelBuilder.Entity("Edzoterem.Domain.Entities.Edzo", b =>
                {
                    b.Navigation("CsoportosFoglalkozasok");

                    b.Navigation("Elerhetosegek");
                });

            modelBuilder.Entity("Edzoterem.Domain.Entities.Munkakor", b =>
                {
                    b.Navigation("Dolgozok");
                });

            modelBuilder.Entity("Edzoterem.Domain.Entities.SzolgaltatasTipus", b =>
                {
                    b.Navigation("EgyeniFoglalkozasok");
                });

            modelBuilder.Entity("Edzoterem.Domain.Entities.Tag", b =>
                {
                    b.Navigation("Berletek");

                    b.Navigation("CsoportosJelentkezesek");

                    b.Navigation("EgyeniFoglalkozasok");

                    b.Navigation("Felhasznalo");
                });
#pragma warning restore 612, 618
        }
    }
}
